### ISSUE TITLE
Set up Unit Tests

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Aztec-Android#1]
It would be great to have to robolectric tests we can run on travis.

**Comment by theck13** [comment]
Robolectric says "No" to Nougat.

`java.lang.UnsupportedOperationException: Robolectric does not support API level 24.`

An [issue](https://github.com/robolectric/robolectric/issues/2554) was created on the Robolectric GitHub repository a few days ago.  We can hope they update soon, but they took a while updating to [API 22](https://github.com/robolectric/robolectric/issues/1728) and [API 23](https://github.com/robolectric/robolectric/issues/1865).  In the meantime, we can still run Robolectric tests if we change the `aztec/build.gradle` to `targetSdkVersion 23`.
