### ISSUE TITLE
Last Style is Applied to Entire Row When Adding Character to End

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#102]
### Expected
Preceding style is preserved when text is added to the end of a line.

### Observed
The style at the end of the line is applied to the entire line.

### Reproduced
1. Enter text like **Bold**_Italic_~~Strike~~.
2. Place cursor at end of line (i.e. after **Bold**_Italic_~~Strike~~).
3. Enter new text.
4. Notice previous style becomes ~~BoldItalicStrike~~.

#### Tested
LG G4 (LG-H815) on Android 6.0.1 with AztecDemo 1.0

**Comment by khaykov** [comment]
Can't seems to reproduce this. But I noticed this happens when you select word suggestion from dropdown menu. Do you get same result every time?

**Comment by theck13** [comment]
Here's an example.  In the animation, I tapped the letter A on the keyboard, the Undo button, the HTML button, and the HTML button again.

![test](https://cloud.githubusercontent.com/assets/3827611/19544640/94014a0a-963d-11e6-910a-2eb024f7b768.gif)

**Comment by khaykov** [comment]
Thanks for a gif! The key was using the soft keyboard. Will look into it :)
