### ISSUE TITLE
Nested lists get removed

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#126]
When going from visual mode to HTML, the inner nested lists get removed.

### Expected

```
<ul>
   <li>Item
   <ul>
      <li>Inner item</li>
   </ul>
   </li>
</ul>
```

### Observed

```
<ul>
   <li>Item</li>
</ul>Inner item
```

### Reproduced
1. Start with a nested list inside a list
2. Switch to visual mode
3. Switch back to HTML mode and notice the change

**Comment by khaykov** [comment]
Looks like scope @hypest's fix for #188 expanded and now includes nested block element parsing which solves problems like this. So I'm going to unasign from this issue for now, to avoid potential merging hell.
