### ISSUE TITLE
Removing the first item does not renumber list

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#128]
Removing the first item of an ordered list does not renumber the rest of the list. 

Use the following HTML and press backspace at the beginning of the 1st line:

```
TEXT
<ol>
  <li>a</li>
  <li>b</li>
  <li>c</li>
</ol>
```

### Before

![screenshot_1478600412](https://cloud.githubusercontent.com/assets/1522856/20095345/71a7e0c8-a5a5-11e6-816a-ef93f4fb5cfa.png)

### After

![screenshot_1478600381](https://cloud.githubusercontent.com/assets/1522856/20095357/7845e524-a5a5-11e6-9ff8-53d9876232f7.png)

**Comment by khaykov** [comment]
Was fixed in #203
