### ISSUE TITLE
Extra newline inserted above block elements

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#146]
If there is a `<br>` above a block element at the beginning of the text, for example:
```
<br>
<h1>Headline</h1>
```
When switched to visual mode there is an extra newline: `\n\nHeadline`.

**Comment by theck13** [comment]
This only occurs if it is at the beginning for the text.  If any other text exists before, it behaves as expected.  See the screenshots below for examples.  These examples only use heading, but ordered and unordered lists show the same behavior.

![newlines](https://cloud.githubusercontent.com/assets/3827611/21247775/5823f968-c2ef-11e6-92f4-63e9450d6d33.png)

**Comment by 0nko** [comment]
That's right. This is a test for it:
```
    @Test
    @Throws(Exception::class)
    fun  parseHtmlToSpanToHtmlLinebreakFollowedByList_isEqual() {
        val input = "<br><ol><li></li><li>a</li><br></ol>"
        val span = SpannableString(mParser.fromHtml(input, context))
        Assert.assertEquals("\n\na\n\n", span.toString())
        val output = mParser.toHtml(span)
        Assert.assertEquals(input, output)
    }
```
