### ISSUE TITLE
Newlines Between Lists and Quotes is Removed After Toggling HTML

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#168]
### Expected
Trailing newlines are retained after toggling to HTML and back for both lists and quotes.

### Observed
Trailing newlines are removed after toggling to HTML and back for both lists and quotes.

![01](https://cloud.githubusercontent.com/assets/3827611/21707584/a9f600fc-d38d-11e6-847f-4c3706b553f0.png)

![02](https://cloud.githubusercontent.com/assets/3827611/21707585/aa02d5a2-d38d-11e6-912b-011a2b5c33f8.png)

![03](https://cloud.githubusercontent.com/assets/3827611/21707586/aa081ab2-d38d-11e6-8d99-068513ff6b65.png)

![04](https://cloud.githubusercontent.com/assets/3827611/21707587/aa09759c-d38d-11e6-935b-1eb7642bd986.png)

### Reproduced
1. Enter ordered list, unordered list, and quote like first screenshot above.
2. Tap ***HTML*** format button.
3. Notice HTML like second screenshot above.
4. Tap ***HTML*** format button.
5. Notice text formatted like third screenshot above.
6. Tap ***HTML*** format button.
7. Notice HTML like fourth screenshot above.

#### Tested
Google Pixel on Android 7.1.1 with AztecDemo 1.0

**Comment by 0nko** [comment]
I just noticed this is happening around headings. Try adding a newline after every heading in the testing app and switch to HTML.

**Comment by hypest** [comment]
Issue doesn't seem to happen anymore. I'll close this issue.

Note, @0nko 's comment above still happens though so, I'll open that as a new ticket.
