### ISSUE TITLE
HTML Toggles List with Quote and Quote with List

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#170]
### Expected
HTML is retained when toggling between visual and HTML views.

### Observed
HTML toggles list within quote to quote within list and vice versa when tapping the HTML button multiple times.

### Reproduced
1. Tap ***HTML*** format button.
2. Enter the following in HTML.
```
<ol>
  <li>
    <blockquote>
        Ordered Quote
    </blockquote>
  </li>
</ol>
```
3. Tap ***HTML*** format button.
4. Notice ordered list with quote.
5. Tap ***HTML*** format button.
6. Notice HTML has changed to the following.
```
<blockquote>
  <ol>
    <li>
        Ordered Quote
    </li>
  </ol>
</blockquote>
```
7. Tap ***HTML*** format button.
8. Notice quote with ordered list.

#### Tested
Google Pixel on Android 7.1.1 with AztecDemo 1.0

**Comment by hypest** [comment]
It seems that this is an issue with Nougat: https://code.google.com/p/android/issues/detail?id=229861#c5

I've tried this on a 6.0 emulator and the order is preserved after the toggling.

**Comment by hypest** [comment]
BTW, API 24 and 25 emulators experience the issue.

**Comment by hypest** [comment]
Removing this ticket from milestone 1.0 as it only affects APIs 24 and 25 and we can accommodate those later.
