### ISSUE TITLE
Cursor Moves Above Block Elements When Toggling HTML View

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#178]
### Expected
Cursor remains in the same position when switching between visual and HTML views.

### Observed
Cursor moves backward one position when going from visual view to HTML view when positioned in text above block elements.

### Reproduced
1. Tap ***HTML*** format button.
2. Enter the following in HTML.
```
Text
<h1>
    Block
</h1>
```
3. Position the cursor at the end of ```Text```.
4. Tap ***HTML*** format button.
5. Notice cursor position is retained.
6. Tap ***HTML*** format button.
7. Notice cursor moved backward one position.

#### Tested
Google Pixel on Android 7.1.1 with AztecDemo 1.0

**Comment by hypest** [comment]
Fixed with #210.
