### ISSUE TITLE
Tapping a heading from toolbar doesn't stick when editor is empty

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Aztec-Android#186]
### Expected
With the editor empty, expected to tap a heading on the toolbar and have it stick (like tapping "bold" does)

### Observed
Heading doesn't stick (and toolbar button stays unselected)

### Reproduced
1. Empty the whole editor
2. Tap the "T" toolbar button to enter Heading1
3. Observe that the toolbar button hasn't turned into selected.
4. Enter some text and notice that it doesn't get styled with Heading1

#### Tested
Nexus 5X, Android v7.1.1

**Comment by 0nko** [comment]
Already fixed.
