### ISSUE TITLE
Handle image display like visual editor

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#201]
~~The hybrid visual editor always shows images on a separate line, i.e. they are displayed like block elements. This should be the same in Aztec.~~

Support image download and sizing that mimics the visual editor.

**Comment by hypest** [comment]
Is this ticket accurate? It seems that an inline image is not always displayed on a separate line on the current production visual editor. Example post that is displayed inline: https://stefanosuser.wordpress.com/2017/01/26/imgs/

**Comment by 0nko** [comment]
Hmm, when I was comparing the visual editor with the previous state of Aztec I compared a few Hogwarts posts with images and all of them were had screen-wide. I guess they were just formatted like that.
