### ISSUE TITLE
Typing right next to an image hides the text

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#204]
### Observed
When typing right next to an image, the text is hidden inside it.

### Reproduced
1. Place a cursor next to an image
2. Type something
3. No text is visible

**Comment by theck13** [comment]
This looks like a consequence of the changes in https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/202.   I can't reproduce the behavior in `develop`, but I can reproduce it in `issue/201-image-blocks`.
