### ISSUE TITLE
Insert Link: Prefill URL field with clipboard contents if appropriate

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Aztec-Android#230]
It would be nice if the editor was smart enough to recognize when the clipboard contains a URL, and pre-fill that field when inserting a link. The common flow is to open the browser, copy a link, and then switch back to the WordPress app to insert it in a post.

iOS: https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/250

**Comment by khaykov** [comment]
This feature is already implemented in editor, and should work as you described. Have you tried it and it didn't worked? Url will not be pre-filled if you open a dialog while your cursor is on another link (it will be pre-filled instead).

**Comment by hoverduck** [comment]
Ah, awesome.  Sorry, I haven't actually seen the Aztec demo yet, I was just writing up issues out of @catehstn's Empathy Challenge and didn't want to waste time writing it against the old editor.  If it's already there, I'll close this one.

Thanks
