### ISSUE TITLE
Weird cursor behavior when deleting text in a Blockquote

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Aztec-Android#236]
### Expected
To be able to delete the text inside a blockquote.

https://cloudup.com/cdkKnz7D0UT

#### Tested
Nexus 5X on 7.1.1 with Integration branch.

**Comment by theck13** [comment]
This <i>might</i> be related to https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/213.

**Comment by 0nko** [comment]
Fixed by #278.
