### ISSUE TITLE
Text Inside Paragraph Moves Outside Block Format When Toggling HTML

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#247]
### Expected
Text remains inside block format when toggling HTML view.

### Observed
Text is moved outside block format when toggling HTML view.  This produces unformatted text above an empty list (for ordered list and unordered list) or removes the block format completed (for quote).  See the screenshots below for examples.

![paragraph](https://cloud.githubusercontent.com/assets/3827611/24050862/d5565d7e-0af5-11e7-95bc-bcf8e209887f.png)

### Reproduced
1. Tap ***HTML*** format button.
2. Enter `<p>hello</p>`.
3. Tap ***HTML*** format button.
4. Tap block format button (i.e. ***Ordered List***, ***Unordered List***, or ***Quote***).
5. Notice `hello` is inside block format.
6. Tap ***HTML*** format button.
7. Notice `hello` is outside block format.
a. If ordered list, empty list is below `hello`.
b. If unordered list, empty list is below `hello`.
c. If quote, format is removed completely.

#### Tested
Google Pixel on Android 7.1.1 with AztecDemo 1.0

**Comment by hypest** [comment]
Fixed with #278 . But, a new issue was introduced in the process: https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/304
