### ISSUE TITLE
Add support for preformatted text ("pre" tag)

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Aztec-Android#262]
### Expected

At a minimum, I expect text within `pre` tags to be displayed in Aztec (without special formatting).

It would be nice for Aztec to also support the `pre` tag by representing preformatted text in a different style (similar to Calypso).

### Observed

Any text within `pre` tags is represented only by a question mark. The text itself doesn't appear.

This HTML:

`vestibulum libero. Nullam mattis tempor viverra.`
`<pre>This is preformatted text.</pre>`
`And regular text.`

Appears like this in Aztec:

![screen shot 2017-02-16 at 11 15 50 am](https://cloud.githubusercontent.com/assets/8658164/23019338/b2a644b0-f439-11e6-8f2d-a5daf9f0f5b1.png)

#### Tested
Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-35

**Comment by 0nko** [comment]
There already exists an issue for this #164.

**Comment by rachelmcr** [comment]
Oops! That issue didn't come up in my search. I'll close this one.
