### ISSUE TITLE
Changes to image settings aren't saved

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Aztec-Android#263]
### Expected

I expect to be able to tap on an image to edit its image settings, and have those changes reflected in the post.

### Observed

I can tap on an image to open its settings, but any changes I make there are lost.

### Reproduced
1. Create a new post.
2. Add an image.
3. Tap the image to open the image settings.
4. Make a change to the image (e.g. add a caption, change the alignment).
5. Tap "Save" to save the changes.
6. Check the HTML and note that the changes don't appear there.
7. Tap again to open the image settings and note that the changes don't appear there.

#### Tested
Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-35

**Comment by theck13** [comment]
Post image settings are specific to the WordPress app.  I'll close this issue and open a new one in the [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android) repository.
