### ISSUE TITLE
Double space to end sentence inserts a space before the period.

### ISSUE THREAD

**Issue by zandyring** [wordpress-mobile/WordPress-Aztec-Android#264]
### Expected
I expect a double space to insert a period at the end of the previous word. `abc.`

### Observed
A double space inserts a space+period after the last word. `abc .`

### Reproduced
1. Type a word in the content area
2. Tap a space twice rapidly
3. You will see a space+period at the end of the last typed word.

#### Tested
Moto G (3rd Gen) on Android 6.0 with alpha-35

**Comment by rachelmcr** [comment]
I see the same behavior on my Nexus 9, Android 7.1.1, WPAndroid alpha-35.

**Comment by khaykov** [comment]
Same as with #266, this seems like a feature exclusive to of iOS hybrid editor.
It would certainly be nice to have, with the ability to turn it on/off with a flag.

**Comment by theck13** [comment]
This is another bug which various by Android version.  On pre-Lollipop versions (API <= 19), tapping double space after "Test" produces "Text. " as expected.  On Lollipop and after (API > 19), tapping double space after "Text" produces "Text ." which is unexpected.
