### ISSUE TITLE
Both the title and content fields do not auto-capitalize the first letter

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Aztec-Android#266]
### Expected
When inputing text into the editor, I expect the first letter to be capitalized.

### Observed
The text isn't capitalized

### Reproduced
1. Open the editor
2. Type a word in both the Title and Content field

#### Tested
Nexus 6P on 7.1.2 with alpha-35

**Comment by khaykov** [comment]
Looks like this is a feature of iOS hybrid editor. It's not in Calypso or andorid editor.
I think it would be a good idea to add it with a flag like `aztec:capitalizeFirstCharacter`, or maybe even separate it for title and content.

**Comment by kwonye** [comment]
It's not in Calypso for the desktop, but on the mobile web it's there for both platforms. Auto-capitalization is standard imo.

**Comment by rachelmcr** [comment]
Auto capitalization is a feature in the Gboard keyboard settings on my Android device (Nexus 9, Android 7.1.1). In Android settings > Language & input > Virtual keyboard > Gboard > Text correction, I have the option to enable "Auto capitalization" (and other features such as "Double-space period") which I expect to work in the app when enabled on my device.

**Comment by 0nko** [comment]
I'm currently busy with Aztec, but I have my groundskeeper rotation next week, so if it can wait I'll try to tackle it then.

**Comment by theck13** [comment]
I think it's better to implement this on the client side (e.g. WordPress-Android) with `android:inputType` rather than in the library (i.e. WordPress-Aztec-Android) with `aztec:capitalizeFirstCharacter`.  I'll close this issue and open a new one in the [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android) repository.
