### ISSUE TITLE
Content after a youtube url does not show up

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Aztec-Android#267]
### Expected
When adding a youtube url along with content afterwards, the content should show in the post.

### Observed
When adding a youtube url along with content afterwards, the content disappears. (see https://dubkwon.wordpress.com/2017/02/20/hajajajajja/)

### Reproduced
1. Open the editor
2. Paste a youtube url
3. A few lines under, type something.
4. Publish the post and notice how the content after the embed isn't part of the post

#### Tested
Nexus 6P on 7.1.2 with alpha-35

**Comment by hypest** [comment]
From my investigation: this must have something to do with the `mShowNewEditor` and `mShowAztecEditor` flags.

**Comment by theck13** [comment]
I can't reproduce this and verified the same behavior with @kwonye.
