### ISSUE TITLE
Delete image with backspace doesn't work

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Aztec-Android#268]
### Expected
Placing the cursor after an image (to the right of the image) and hitting backspace should delete the image

### Observed
Placing the cursor after an image (to the right of the image) and hitting backspace does not delete the image, and inserts the string "& # X200b;"
![screenshot_20170219-145549](https://cloud.githubusercontent.com/assets/6597771/23127307/515d88ee-f759-11e6-9aca-780892d336f6.png)

### Reproduced
1. Open the editor
2. Insert an image
3. Place the cursor to the right of the image
4. hit Backspace one or two times
5. observe the image is not deleted and the string "& # X200b;" is inserted below it.

#### Tested
[Google Pixel] on [7.1.1] with [develop branch 6.8]

**Comment by daniloercoli** [comment]
Is this issue for Aztec or the old editor? If the old one I think can mark it as Aztec-obsolete and don't fix it.

**Comment by 0nko** [comment]
This is the old visual editor.

**Comment by mzorz** [comment]
:man_facepalming: thanks for double checking @0nko ! 🙇

**Comment by 0nko** [comment]
No worries ;)
