### ISSUE TITLE
Add ability to remove list styling with backspace

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Aztec-Android#73]
When cursor is positioned right after bullet/number and backspace is pressed remove list style from the line.

**Comment by hypest** [comment]
Hey @khaykov , currently, pressing backspace does remove the list styling and moves the trailing text into the list item above the deleted one, but not when trying to backspace on the very first list item when that item is at the top of the EditText. Is that the case you're referring to perhaps, or something else? Thanks!

**Comment by khaykov** [comment]
Yes, I think when the issue was opened there were some problems with removing list styling from any line. Now it's only the case for the first one.
