### ISSUE TITLE
Continue Styling Text with Header Style Applied

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#74]
### Expected

After applying a header style, continue to style text added to the header.
### Observed

As commented [here](https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/70#issuecomment-244872045), headers cannot be extended without reapplying the style.
### Reproduced
1. Select a line of text.
2. Tap header format button.
3. Choose header style.
4. Select end of line of header.
5. Add text to header.
6. Notice added text is not styled.
#### Tested

LG G4 (LG-H815) on Android 6.0.1 with AztecDemo 1.0

**Comment by theck13** [comment]
@khaykov, which code were you referring to with this comment?
> We probably should fix this a bit later - opening/closing of spans is something that is already mostly solved with inline styles and lists ( #71 ) so we could reuse some of that code to deal with headers (and Quote) too.

**Comment by khaykov** [comment]
@theck13 [This](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L1341) one.
It was some time ago, but the idea with inline styles was to keep spans closed all the time, and extend them as you type.

**Comment by khaykov** [comment]
And [block styling](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L1371) too. Headers are kinda mix of both, so I'm not sure about the right approach yet. We have only one line and one span to care about, so it shouldn't be that complicated.
